### ISSUE TITLE
Charge paid date

### ISSUE THREAD

**Issue by ASG09** [mjr/juno-python#1]
Hello Manaia, I was digging in your code to try to retrieve a charge paid date. Testing a charge I have manually marked as paid (as a test), I can't find within the json response from `mycharge.charge.find_by_id()` the date it was marked as paid.

The [documentation](https://dev.juno.com.br/api/v2#operation/findById) shows that this information should be retrieved in a 200 response under the 'payments' label (and the date also appears at Juno's application interface). Do you know how to retrieve the paid date or do you know if this is not possible at all via juno's API?

Thank you and excellent work!

**Comment by mjr** [comment]
Hello Andre, you can get it from a charge, with something like:

```python
result = charge.find_by_id("charge_id")
print(result.charge.payments[0].release_date)
```

**Comment by ASG09** [comment]
I tried that, I get a 

> AttributeError: 'result' object has no attribute 'payments'

because if you look within the result object there isn't really a payments attribute:

> <SuccessfulResult {charge: <Charge {id: 'some_id', code: some_code, reference: '', due_date: 'some_due_date', checkout_url: 'https://pay.juno.com.br/checkout/some_letters', amount: 9.17, status: 'MANUAL_RECONCILIATION', _links: {'self': {'href': 'https://api.juno.com.br/api-integration/charges/some_id'}}} at some_numbers>} at and_more_numbers>

perhaps this has something to do with the way this charge was paid? (manually marked as paid, as showed by 'MANUAL_RECONCILIATION')?

**Comment by ASG09** [comment]
I've tried paying a 0.42 charge and now the payments attribute appears. That might be the reason. So probably it's an API limitation. Thank you anyway!
