### ISSUE TITLE
Plans/Subscriptions endpoint

### ISSUE THREAD

**Issue by leogregianin** [mjr/juno-python#6]
Create subscription plans to bill your customers on a recurring basis.
Doc: https://dev.juno.com.br/api/v2#tag/Assinatura

**Comment by mjr** [comment]
Thanks @leogregianin for adding this functionality, I am doing a refactoring in some points of the lib, I will add these features along with the refactoring.

**Comment by leogregianin** [comment]
@mjr, ok. I'm already using it in production with no problems.

**Comment by mjr** [comment]
Added 👍
