### ISSUE TITLE
Charge find_all with more parameters

### ISSUE THREAD

**Issue by leogregianin** [mjr/juno-python#7]
When using ```juno.charge.find_all()``` to be able to use any endpoint query parameters in doc ref: https://dev.juno.com.br/api/v2#operation/listCharges

**Comment by mjr** [comment]
Thanks @leogregianin for adding this functionality, I am doing a refactoring in some points of the lib, I will add these features along with the refactoring.

**Comment by mjr** [comment]
Added [filter adjustment](https://github.com/mjr/juno-python/commit/643e2d51e1627c307d9358913952369bbf6ca9b8) :+1:
